### PR TITLE
Helped you with NiCSS! :D

### PR DESCRIPTION
**Pull request by zbee**
Hey John,

I cleaned up some of your work in NiCSS, sorry if that came off rude-like ...

Updated readm.md: Fixed the pronunciation of NICSS
Updated readme.md again: Fixed pronunciation of NICSS, again
Updated /lib/nicss.js: Took out "Effing", replaced with "Super"
Updated readme.md: Clarified some stuff, added punctuation

Sincerely,
Ethan (Zbee)

### CODE REVIEW

**Comment by zbee** [comment]
I also edited the like information stuff ... Like, it's right under the "Code" tab ... Whatever, I changed it to this:

Nice CSS :) - So Feaking alpha it hurts, not for production yet. Want to help? Go ahead!

Sincerely,
Ethan (Zbee)

**Comment by nijikokun** [comment]
Not at all, I was reading the edits as you did them :P

**Comment by zbee** [comment]
:)

Wait, so like, you wen to ZbeeDEV/NiCSS? Or did they show up instantly?

Sincerely,
Ethan (Zbee)

**Comment by nijikokun** [comment]
I went to your fork and read them. :D

**Comment by zbee** [comment]
Omg, that's awesome =D

In case you didn't know, I love your work :)

Sincerely,
Ethan (Zbee)

**Pull request merged**
